version: '2'
services:

  outland_server:
    build: .
    environment:
      # see configuration-docker.yaml for context
      - OUTLAND_FEATURE_BASE_URI
      - OUTLAND_FEATURE_API_IDLE_TO
      - OUTLAND_FEATURE_DYNAMODB_URL
      - OUTLAND_FEATURE_DYNAMODB_REGION
      - OUTLAND_FEATURE_TABLE_FEATURES
      - OUTLAND_FEATURE_TABLE_GROUPS
      - OUTLAND_FEATURE_TABLE_GRAPHS
      - OUTLAND_FEATURE_AUTH_BASIC_ENABLED
      - OUTLAND_FEATURE_AUTH_BASIC_API_KEYS
      - OUTLAND_FEATURE_AUTH_BASIC_CACHE_SECONDS
      - OUTLAND_FEATURE_AUTH_OAUTH_ENABLED
      - OUTLAND_FEATURE_AUTH_OAUTH_SCOPE_POLICY
      - OUTLAND_FEATURE_AUTH_OAUTH_CACHE_SECONDS
      - OUTLAND_FEATURE_REMOTE_OAUTH_SERVER
      - OUTLAND_FEATURE_AUTH_OAUTH_CONN_TO
      - OUTLAND_FEATURE_AUTH_OAUTH_READ_TO
      - OUTLAND_FEATURE_ANY_GROUP_ACCESS
      - OUTLAND_FEATURE_REDIS_MAXCONN
      - OUTLAND_FEATURE_REDIS_CACHE_HOST
      - OUTLAND_FEATURE_REDIS_CACHE_PORT
      - OUTLAND_FEATURE_REDIS_IDEM_HOST
      # set jvm options here
      - JAVA_OPTS
      # aws client env if you're using the "credentials" option
      - AWS_ACCESS_KEY_ID
      - AWS_SECRET_ACCESS_KEY
      - OUTLAND_FEATURE_AWS_AUTHMODE

    ports:
     - "8180:8180"
     - "8181:8181"
    links:
     - dynamodb
     - redis
    volumes:
      - ../src/main/resources:/outland/conf

  redis:
    image: redis
    ports:
      - "6379:6379"

  dynamodb:
    image: deangiberson/aws-dynamodb-local
    ports:
      - "8000:8000"
