#!/usr/bin/env bash

version=`cat ../../gradle.properties | grep "version" | cut -d= -f2`

public_name="dehora/outland-feature-server"

echo "Publishing ${public_name} ${version}"
echo "---------------------------------------------------------------"

./build_service

export OUTLAND_VERSION=${version}
docker build -t $public_name:latest .
docker build -t $public_name:$version .
docker push $public_name:latest
docker push $public_name:$version