serviceName: Outland Feature Service
environment: development

baseURI: http://localhost:8180

server:
  registerDefaultExceptionMappers: false
  applicationConnectors:
    - type: http
      port: 8280
      idleTimeout: 8 seconds
  adminConnectors:
    - type: http
      port: 8281

redis:
  servers:
    - name: outland_feature_cache_redis
      host: localhost
      port: 6379
      maxConnections: 8
    - name: outland_feature_idempotency_check_redis
      host: localhost
      port: 6379
      maxConnections: 8

logging:
  level: INFO
  appenders:
    - type: console
      timeZone: UTC
      threshold: INFO
      target: stderr
    - type: file
      currentLogFilename: /tmp/application.log
      archive: false
      timeZone: UTC

aws:
  environment: test
  accessKey: AWS_KEY
  secretKey: AWS_SECRET
  dynamoDbUrl: http://localhost:8001
  signingRegion: eu-central-1

auth:
  # basic exists mostly for dev, test and local docker. Always enable oauth for production. The main
  # scenario for enabling basic in prod is to allow a management ui to make requests for all apps via
  # a shared secret.
  basicEnabled: true
  # basic_app_username_password_keys: use the values in basicAuthenticationKeys as global api keys
  basicAuthenticationPolicy: basic_app_username_password_keys
  # set a comma separated list of keys via the DW_API_KEYS envar
  basicAuthenticationKeys: ${FEATURE_API_KEYS}
  # basic_disable_scope_check: ignore scope checks for api requests
  basicScopePolicy: basic_disable_scope_check

  oauthEnabled: false
  # oauth_bearer_reflect: return the bearer token as the app id (for local testing with token services)
  oauthAuthenticationPolicy: oauth_bearer_reflect
  # oauth_disable_scope_check: don't check scopes
  oauthScopePolicy: oauth_disable_scope_check