serviceName: Outland Feature Service
environment: development

server:
  registerDefaultExceptionMappers: false
  applicationConnectors:
    - type: http
      port: 8280
      idleTimeout: 8 seconds
  adminConnectors:
    - type: http
      port: 8281

redis:
  servers:
    - name: outland_feature_cache_redis
      host: localhost
      port: 6379
      maxConnections: 8
    - name: outland_feature_idempotency_check_redis
      host: localhost
      port: 6379
      maxConnections: 8

logging:
  level: INFO
  appenders:
    - type: console
      timeZone: UTC
      threshold: INFO
      target: stderr
    - type: file
      currentLogFilename: /tmp/application.log
      archive: false
      timeZone: UTC

aws:
  environment: test
  accessKey: AWS_KEY
  secretKey: AWS_SECRET
  dynamoDbUrl: http://localhost:8001
  signingRegion: eu-central-1