// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: outland.proto

package outland.feature.proto;

public final class FeatureMessage {
  private FeatureMessage() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_outland_FeatureOwner_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_outland_FeatureOwner_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_outland_FeatureVersion_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_outland_FeatureVersion_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_outland_FeatureOption_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_outland_FeatureOption_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_outland_Feature_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_outland_Feature_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_outland_Feature_PropertiesEntry_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_outland_Feature_PropertiesEntry_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_outland_FeatureCollection_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_outland_FeatureCollection_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_outland_App_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_outland_App_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_outland_Service_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_outland_Service_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_outland_Owner_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_outland_Owner_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\routland.proto\022\007outland\"W\n\014FeatureOwner" +
      "\022\014\n\004type\030\001 \001(\t\022\014\n\004name\030\002 \001(\t\022\r\n\005email\030\003 " +
      "\001(\t\022\020\n\010username\030\004 \001(\t\022\n\n\002id\030\005 \001(\t\"N\n\016Fea" +
      "tureVersion\022\n\n\002id\030\001 \001(\t\022\021\n\ttimestamp\030\002 \001" +
      "(\003\022\017\n\007counter\030\003 \001(\003\022\014\n\004type\030\004 \001(\t\"{\n\rFea" +
      "tureOption\022\n\n\002id\030\001 \001(\t\022#\n\006option\030\002 \001(\0162\023" +
      ".outland.OptionType\022\014\n\004name\030\003 \001(\t\022\r\n\005val" +
      "ue\030\004 \001(\t\022\016\n\006weight\030\005 \001(\005\022\014\n\004type\030\006 \001(\t\"\311" +
      "\003\n\007Feature\022\n\n\002id\030\001 \001(\t\022\013\n\003key\030\002 \001(\t\022\016\n\006a" +
      "ppkey\030\003 \001(\t\022%\n\005state\030\004 \001(\0162\026.outland.Fea",
      "ture.State\022\023\n\013description\030\005 \001(\t\022\017\n\007creat" +
      "ed\030\006 \001(\t\022\017\n\007updated\030\007 \001(\t\022$\n\005owner\030\010 \001(\013" +
      "2\025.outland.FeatureOwner\0224\n\nproperties\030\t " +
      "\003(\0132 .outland.Feature.PropertiesEntry\022#\n" +
      "\006option\030\n \001(\0162\023.outland.OptionType\022\'\n\007op" +
      "tions\030\013 \003(\0132\026.outland.FeatureOption\022(\n\007v" +
      "ersion\030\014 \001(\0132\027.outland.FeatureVersion\022\014\n" +
      "\004type\030\r \001(\t\0321\n\017PropertiesEntry\022\013\n\003key\030\001 " +
      "\001(\t\022\r\n\005value\030\002 \001(\t:\0028\001\"\"\n\005State\022\010\n\004none\020" +
      "\000\022\007\n\003off\020\001\022\006\n\002on\020\002\"R\n\021FeatureCollection\022",
      "\014\n\004type\030\001 \001(\t\022\016\n\006appkey\030\002 \001(\t\022\037\n\005items\030\003" +
      " \003(\0132\020.outland.Feature\"\240\001\n\003App\022\n\n\002id\030\001 \001" +
      "(\t\022\013\n\003key\030\002 \001(\t\022\014\n\004name\030\003 \001(\t\022\017\n\007created" +
      "\030\006 \001(\t\022\017\n\007updated\030\007 \001(\t\022\"\n\010services\030\004 \003(" +
      "\0132\020.outland.Service\022\036\n\006owners\030\005 \003(\0132\016.ou" +
      "tland.Owner\022\014\n\004type\030\010 \001(\t\"`\n\007Service\022\n\n\002" +
      "id\030\001 \001(\t\022\013\n\003key\030\002 \001(\t\022\014\n\004name\030\003 \001(\t\022\017\n\007c" +
      "reated\030\006 \001(\t\022\017\n\007updated\030\007 \001(\t\022\014\n\004type\030\010 " +
      "\001(\t\"r\n\005Owner\022\n\n\002id\030\001 \001(\t\022\014\n\004name\030\002 \001(\t\022\020" +
      "\n\010username\030\003 \001(\t\022\r\n\005email\030\004 \001(\t\022\017\n\007creat",
      "ed\030\005 \001(\t\022\017\n\007updated\030\006 \001(\t\022\014\n\004type\030\007 \001(\t*" +
      " \n\nOptionType\022\010\n\004flag\020\000\022\010\n\004bool\020\001B+\n\025out" +
      "land.feature.protoB\016FeatureMessageH\001P\001b\006" +
      "proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_outland_FeatureOwner_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_outland_FeatureOwner_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_outland_FeatureOwner_descriptor,
        new java.lang.String[] { "Type", "Name", "Email", "Username", "Id", });
    internal_static_outland_FeatureVersion_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_outland_FeatureVersion_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_outland_FeatureVersion_descriptor,
        new java.lang.String[] { "Id", "Timestamp", "Counter", "Type", });
    internal_static_outland_FeatureOption_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_outland_FeatureOption_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_outland_FeatureOption_descriptor,
        new java.lang.String[] { "Id", "Option", "Name", "Value", "Weight", "Type", });
    internal_static_outland_Feature_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_outland_Feature_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_outland_Feature_descriptor,
        new java.lang.String[] { "Id", "Key", "Appkey", "State", "Description", "Created", "Updated", "Owner", "Properties", "Option", "Options", "Version", "Type", });
    internal_static_outland_Feature_PropertiesEntry_descriptor =
      internal_static_outland_Feature_descriptor.getNestedTypes().get(0);
    internal_static_outland_Feature_PropertiesEntry_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_outland_Feature_PropertiesEntry_descriptor,
        new java.lang.String[] { "Key", "Value", });
    internal_static_outland_FeatureCollection_descriptor =
      getDescriptor().getMessageTypes().get(4);
    internal_static_outland_FeatureCollection_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_outland_FeatureCollection_descriptor,
        new java.lang.String[] { "Type", "Appkey", "Items", });
    internal_static_outland_App_descriptor =
      getDescriptor().getMessageTypes().get(5);
    internal_static_outland_App_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_outland_App_descriptor,
        new java.lang.String[] { "Id", "Key", "Name", "Created", "Updated", "Services", "Owners", "Type", });
    internal_static_outland_Service_descriptor =
      getDescriptor().getMessageTypes().get(6);
    internal_static_outland_Service_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_outland_Service_descriptor,
        new java.lang.String[] { "Id", "Key", "Name", "Created", "Updated", "Type", });
    internal_static_outland_Owner_descriptor =
      getDescriptor().getMessageTypes().get(7);
    internal_static_outland_Owner_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_outland_Owner_descriptor,
        new java.lang.String[] { "Id", "Name", "Username", "Email", "Created", "Updated", "Type", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
