// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: outland.proto

package outland.feature.proto;

public interface FeatureOptionOrBuilder extends
    // @@protoc_insertion_point(interface_extends:outland.FeatureOption)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>optional string type = 1;</code>
   */
  java.lang.String getType();
  /**
   * <code>optional string type = 1;</code>
   */
  com.google.protobuf.ByteString
      getTypeBytes();

  /**
   * <code>optional string id = 2;</code>
   */
  java.lang.String getId();
  /**
   * <code>optional string id = 2;</code>
   */
  com.google.protobuf.ByteString
      getIdBytes();

  /**
   * <code>optional .outland.OptionType option = 10;</code>
   */
  int getOptionValue();
  /**
   * <code>optional .outland.OptionType option = 10;</code>
   */
  outland.feature.proto.OptionType getOption();

  /**
   * <code>optional string name = 11;</code>
   */
  java.lang.String getName();
  /**
   * <code>optional string name = 11;</code>
   */
  com.google.protobuf.ByteString
      getNameBytes();

  /**
   * <code>optional string value = 12;</code>
   */
  java.lang.String getValue();
  /**
   * <code>optional string value = 12;</code>
   */
  com.google.protobuf.ByteString
      getValueBytes();

  /**
   * <code>optional int32 weight = 13;</code>
   */
  int getWeight();
}
