// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: outland.proto

package outland.feature.proto;

public interface MemberAccessOrBuilder extends
    // @@protoc_insertion_point(interface_extends:outland.MemberAccess)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>optional string type = 1;</code>
   */
  java.lang.String getType();
  /**
   * <code>optional string type = 1;</code>
   */
  com.google.protobuf.ByteString
      getTypeBytes();

  /**
   * <code>optional string id = 2;</code>
   */
  java.lang.String getId();
  /**
   * <code>optional string id = 2;</code>
   */
  com.google.protobuf.ByteString
      getIdBytes();

  /**
   * <code>optional string name = 10;</code>
   */
  java.lang.String getName();
  /**
   * <code>optional string name = 10;</code>
   */
  com.google.protobuf.ByteString
      getNameBytes();

  /**
   * <code>optional string username = 11;</code>
   */
  java.lang.String getUsername();
  /**
   * <code>optional string username = 11;</code>
   */
  com.google.protobuf.ByteString
      getUsernameBytes();

  /**
   * <code>optional string email = 12;</code>
   */
  java.lang.String getEmail();
  /**
   * <code>optional string email = 12;</code>
   */
  com.google.protobuf.ByteString
      getEmailBytes();
}
