// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: outland.proto

package outland.feature.proto;

/**
 * Protobuf enum {@code outland.OptionType}
 */
public enum OptionType
    implements com.google.protobuf.ProtocolMessageEnum {
  /**
   * <pre>
   *A basic feature flag, or toggle. The result for this is always the value of Feature.State
   * </pre>
   *
   * <code>flag = 0;</code>
   */
  flag(0),
  UNRECOGNIZED(-1),
  ;

  /**
   * <pre>
   *A basic feature flag, or toggle. The result for this is always the value of Feature.State
   * </pre>
   *
   * <code>flag = 0;</code>
   */
  public static final int flag_VALUE = 0;


  public final int getNumber() {
    if (this == UNRECOGNIZED) {
      throw new java.lang.IllegalArgumentException(
          "Can't get the number of an unknown enum value.");
    }
    return value;
  }

  /**
   * @deprecated Use {@link #forNumber(int)} instead.
   */
  @java.lang.Deprecated
  public static OptionType valueOf(int value) {
    return forNumber(value);
  }

  public static OptionType forNumber(int value) {
    switch (value) {
      case 0: return flag;
      default: return null;
    }
  }

  public static com.google.protobuf.Internal.EnumLiteMap<OptionType>
      internalGetValueMap() {
    return internalValueMap;
  }
  private static final com.google.protobuf.Internal.EnumLiteMap<
      OptionType> internalValueMap =
        new com.google.protobuf.Internal.EnumLiteMap<OptionType>() {
          public OptionType findValueByNumber(int number) {
            return OptionType.forNumber(number);
          }
        };

  public final com.google.protobuf.Descriptors.EnumValueDescriptor
      getValueDescriptor() {
    return getDescriptor().getValues().get(ordinal());
  }
  public final com.google.protobuf.Descriptors.EnumDescriptor
      getDescriptorForType() {
    return getDescriptor();
  }
  public static final com.google.protobuf.Descriptors.EnumDescriptor
      getDescriptor() {
    return outland.feature.proto.FeatureMessage.getDescriptor()
        .getEnumTypes().get(0);
  }

  private static final OptionType[] VALUES = values();

  public static OptionType valueOf(
      com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
    if (desc.getType() != getDescriptor()) {
      throw new java.lang.IllegalArgumentException(
        "EnumValueDescriptor is not for this type.");
    }
    if (desc.getIndex() == -1) {
      return UNRECOGNIZED;
    }
    return VALUES[desc.getIndex()];
  }

  private final int value;

  private OptionType(int value) {
    this.value = value;
  }

  // @@protoc_insertion_point(enum_scope:outland.OptionType)
}

