// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: outland.proto

package outland.feature.proto;

public interface OwnerOrBuilder extends
    // @@protoc_insertion_point(interface_extends:outland.Owner)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>optional string id = 1;</code>
   */
  java.lang.String getId();
  /**
   * <code>optional string id = 1;</code>
   */
  com.google.protobuf.ByteString
      getIdBytes();

  /**
   * <code>optional string name = 2;</code>
   */
  java.lang.String getName();
  /**
   * <code>optional string name = 2;</code>
   */
  com.google.protobuf.ByteString
      getNameBytes();

  /**
   * <code>optional string username = 3;</code>
   */
  java.lang.String getUsername();
  /**
   * <code>optional string username = 3;</code>
   */
  com.google.protobuf.ByteString
      getUsernameBytes();

  /**
   * <code>optional string email = 4;</code>
   */
  java.lang.String getEmail();
  /**
   * <code>optional string email = 4;</code>
   */
  com.google.protobuf.ByteString
      getEmailBytes();

  /**
   * <code>optional string created = 5;</code>
   */
  java.lang.String getCreated();
  /**
   * <code>optional string created = 5;</code>
   */
  com.google.protobuf.ByteString
      getCreatedBytes();

  /**
   * <code>optional string updated = 6;</code>
   */
  java.lang.String getUpdated();
  /**
   * <code>optional string updated = 6;</code>
   */
  com.google.protobuf.ByteString
      getUpdatedBytes();

  /**
   * <code>optional string type = 7;</code>
   */
  java.lang.String getType();
  /**
   * <code>optional string type = 7;</code>
   */
  com.google.protobuf.ByteString
      getTypeBytes();
}
