#!/usr/bin/env bash

echo "Creating Graph Table"
curl --head -XPOST localhost:8181/tasks/DynamoCreateGraphTableTask

echo "Creating Apps Table"
curl --head -XPOST localhost:8181/tasks/DynamoCreateGroupsTableTask

echo "Creating Feature Table"
curl --head -XPOST localhost:8181/tasks/DynamoCreateFeatureTableTask
