#!/usr/bin/env bash

# these are also set in the .env file given to the server on startup
service="testconsole/service"
api_key="letmein"

ikey_app="idemkey-test-acme-group"

curl -i http://localhost:8180/groups \
-u ${service}:${api_key} \
-H "Content-type: application/json" \
-H "Idempotency-Key: ${ikey_app}" \
-d'
{
	"key": "test-acme-group",
	"name": "My Group",
	"owners": {
	  "items":[{
		  "name": "Acme",
		  "username": "acme",
		  "email": "acme@example.org"
		  }
		]
	},
	"granted": {
		"services": [{
			"key": "testservice",
			"name": "Test Service"
		}],
		"members": [{
			"username": "testuser",
			"name": "Test User"
		}]
	}
}
'

echo "Group created, adding some feature flags"

ikey_f1="idemkey-test-acme-group-f1"

curl -i http://localhost:8180/features \
-u ${service}:${api_key} \
-H "Content-type: application/json" \
-H "Idempotency-Key: ${ikey_f1}" \
-d '
{
	"key": "test-flag-1",
	"description": "A feature flag",
	"group": "test-acme-group",
	"owner": {
		"username": "acme",
		"email": "acme@example.org"
	}
}
'

ikey_f2="idemkey-test-acme-group-f2"

curl -i http://localhost:8180/features \
-u ${service}:${api_key} \
-H "Content-type: application/json" \
-H "Idempotency-Key: ${ikey_f2}" \
-d'
{
	"key": "test-option-1",
	"description": "A weighted feature",
	"group": "test-acme-group",
	"options": {
	  "option": "bool",
	  "items": [{
		"name": "false",
		"value": "false",
		"weight": 0
    }, {
      "name": "true",
      "value": "true",
      "weight": 10000
    }]
	},
	"owner": {
		"username": "acme",
		"email": "acme@example.org"
	}
}
'

ikey_f3="idemkey-test-acme-group-f3"

curl -i http://localhost:8180/features \
-u ${service}:${api_key} \
-H "Content-type: application/json" \
-H "Idempotency-Key: ${ikey_f3}" \
-d '
{
	"key": "test-flag-namespace-1",
	"description": "A feature flag with two namespaces",
	"group": "test-acme-group",
	"owner": {
		"username": "acme",
		"email": "acme@example.org"
	},
	"namespaces": {
	   "items": [
	      {
	        "namespace": "staging",
	        "feature": {
	          "key": "test-flag-namespace-1",
            "options": {
              "option": "bool",
              "items": [{
              "name": "false",
              "value": "false",
              "weight": 0
              }, {
                "name": "true",
                "value": "true",
                "weight": 10000
              }]
            }
	        }
	      }
	      ,{
	        "namespace": "production",
	        "feature": {
	          "key": "test-flag-namespace-1",
            "options": {
              "option": "bool",
              "items": [{
              "name": "false",
              "value": "false",
              "weight": 10000
              }, {
                "name": "true",
                "value": "true",
                "weight": 0
              }]
            }
	        }
	      }
	   ]
	}
}
'