#!/usr/bin/env bash

echo "Creating Graph Table"
curl -v -XPOST localhost:8281/tasks/DynamoCreateAppGraphTableTask
echo "Creating Apps Table"
curl -v -XPOST localhost:8281/tasks/DynamoCreateAppsTableTask
echo "Creating Feature Table"
curl -v -XPOST localhost:8281/tasks/DynamoCreateFeatureTableTask