#!/usr/bin/env bash

exec java -server -jar \
-XX:+UseParNewGC \
-XX:+UseConcMarkSweepGC \
-XX:+PrintGCTimeStamps \
-XX:+PrintTenuringDistribution \
-Xloggc:gc.log \
-XX:+UseGCLogFileRotation \
-XX:NumberOfGCLogFiles=1 \
-XX:GCLogFileSize=3M \
-Djava.security.egd=file:/dev/./urandom \
outland-feature-server-*.jar \
server /outland/conf/configuration-local-docker.yaml
