// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: outland-cluster.proto

package outland.cluster.proto;

public final class ClusterMessage {
  private ClusterMessage() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_outland_Rouk_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_outland_Rouk_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_outland_Imok_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_outland_Imok_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_outland_Node_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_outland_Node_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_outland_Response_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_outland_Response_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_outland_JoinMessage_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_outland_JoinMessage_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_outland_JoinReplyMessage_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_outland_JoinReplyMessage_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_outland_ForwardJoinMessage_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_outland_ForwardJoinMessage_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_outland_DisconnectMessage_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_outland_DisconnectMessage_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_outland_NeighborMessage_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_outland_NeighborMessage_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_outland_NeighbourReplyMessage_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_outland_NeighbourReplyMessage_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_outland_ShuffleMessage_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_outland_ShuffleMessage_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_outland_ShuffleReplyMessage_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_outland_ShuffleReplyMessage_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\025outland-cluster.proto\022\007outland\"1\n\004Rouk" +
      "\022\n\n\002id\030\001 \001(\t\022\035\n\006sender\030\002 \001(\0132\r.outland.N" +
      "ode\">\n\004Imok\022\n\n\002id\030\001 \001(\t\022\013\n\003cid\030\002 \001(\t\022\035\n\006" +
      "sender\030\003 \001(\0132\r.outland.Node\".\n\004Node\022\n\n\002i" +
      "d\030\001 \001(\t\022\014\n\004host\030\002 \001(\t\022\014\n\004port\030\003 \001(\005\"<\n\010R" +
      "esponse\022\021\n\trequestId\030\001 \001(\t\022\035\n\006sender\030\002 \001" +
      "(\0132\r.outland.Node\"8\n\013JoinMessage\022\n\n\002id\030\001" +
      " \001(\t\022\035\n\006sender\030\002 \001(\0132\r.outland.Node\"T\n\020J" +
      "oinReplyMessage\022\n\n\002id\030\001 \001(\t\022\035\n\006sender\030\002 " +
      "\001(\0132\r.outland.Node\022\025\n\rcorrelationId\030\003 \001(",
      "\t\"k\n\022ForwardJoinMessage\022\n\n\002id\030\001 \001(\t\022\035\n\006s" +
      "ender\030\002 \001(\0132\r.outland.Node\022\035\n\006joiner\030\003 \001" +
      "(\0132\r.outland.Node\022\013\n\003ttl\030\004 \001(\005\">\n\021Discon" +
      "nectMessage\022\n\n\002id\030\001 \001(\t\022\035\n\006sender\030\002 \001(\0132" +
      "\r.outland.Node\"\220\001\n\017NeighborMessage\022\n\n\002id" +
      "\030\001 \001(\t\022\035\n\006sender\030\002 \001(\0132\r.outland.Node\0223\n" +
      "\010priority\030\003 \001(\0162!.outland.NeighborMessag" +
      "e.Priority\"\035\n\010Priority\022\007\n\003low\020\000\022\010\n\004high\020" +
      "\001\"\270\001\n\025NeighbourReplyMessage\022\n\n\002id\030\001 \001(\t\022" +
      "\035\n\006sender\030\002 \001(\0132\r.outland.Node\022\025\n\rcorrel",
      "ationId\030\003 \001(\t\0229\n\010response\030\004 \001(\0162\'.outlan" +
      "d.NeighbourReplyMessage.Response\"\"\n\010Resp" +
      "onse\022\n\n\006reject\020\000\022\n\n\006accept\020\001\"\214\001\n\016Shuffle" +
      "Message\022\n\n\002id\030\001 \001(\t\022\035\n\006sender\030\002 \001(\0132\r.ou" +
      "tland.Node\022\035\n\006origin\030\003 \001(\0132\r.outland.Nod" +
      "e\022#\n\014exchangeList\030\004 \003(\0132\r.outland.Node\022\013" +
      "\n\003ttl\030\005 \001(\005\"\200\001\n\023ShuffleReplyMessage\022\n\n\002i" +
      "d\030\001 \001(\t\022\035\n\006sender\030\002 \001(\0132\r.outland.Node\022\031" +
      "\n\021originalMessageId\030\003 \001(\t\022#\n\014exchangeLis" +
      "t\030\004 \003(\0132\r.outland.Node2\274\004\n\016OutlandServic",
      "e\0228\n\013JoinRequest\022\024.outland.JoinMessage\032\021" +
      ".outland.Response\"\000\022;\n\tJoinReply\022\031.outla" +
      "nd.JoinReplyMessage\032\021.outland.Response\"\000" +
      "\022F\n\022ForwardJoinRequest\022\033.outland.Forward" +
      "JoinMessage\032\021.outland.Response\"\000\022D\n\021Disc" +
      "onnectRequest\022\032.outland.DisconnectMessag" +
      "e\032\021.outland.Response\"\000\022M\n\017NeighborReques" +
      "t\022\030.outland.NeighborMessage\032\036.outland.Ne" +
      "ighbourReplyMessage\"\000\022>\n\016ShuffleRequest\022" +
      "\027.outland.ShuffleMessage\032\021.outland.Respo",
      "nse\"\000\022A\n\014ShuffleReply\022\034.outland.ShuffleR" +
      "eplyMessage\032\021.outland.Response\"\000\022&\n\004Ruok" +
      "\022\r.outland.Rouk\032\r.outland.Imok\"\000\022+\n\005Ruok" +
      "s\022\r.outland.Rouk\032\r.outland.Imok\"\000(\0010\001B+\n" +
      "\025outland.cluster.protoB\016ClusterMessageH\001" +
      "P\001b\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_outland_Rouk_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_outland_Rouk_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_outland_Rouk_descriptor,
        new java.lang.String[] { "Id", "Sender", });
    internal_static_outland_Imok_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_outland_Imok_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_outland_Imok_descriptor,
        new java.lang.String[] { "Id", "Cid", "Sender", });
    internal_static_outland_Node_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_outland_Node_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_outland_Node_descriptor,
        new java.lang.String[] { "Id", "Host", "Port", });
    internal_static_outland_Response_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_outland_Response_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_outland_Response_descriptor,
        new java.lang.String[] { "RequestId", "Sender", });
    internal_static_outland_JoinMessage_descriptor =
      getDescriptor().getMessageTypes().get(4);
    internal_static_outland_JoinMessage_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_outland_JoinMessage_descriptor,
        new java.lang.String[] { "Id", "Sender", });
    internal_static_outland_JoinReplyMessage_descriptor =
      getDescriptor().getMessageTypes().get(5);
    internal_static_outland_JoinReplyMessage_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_outland_JoinReplyMessage_descriptor,
        new java.lang.String[] { "Id", "Sender", "CorrelationId", });
    internal_static_outland_ForwardJoinMessage_descriptor =
      getDescriptor().getMessageTypes().get(6);
    internal_static_outland_ForwardJoinMessage_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_outland_ForwardJoinMessage_descriptor,
        new java.lang.String[] { "Id", "Sender", "Joiner", "Ttl", });
    internal_static_outland_DisconnectMessage_descriptor =
      getDescriptor().getMessageTypes().get(7);
    internal_static_outland_DisconnectMessage_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_outland_DisconnectMessage_descriptor,
        new java.lang.String[] { "Id", "Sender", });
    internal_static_outland_NeighborMessage_descriptor =
      getDescriptor().getMessageTypes().get(8);
    internal_static_outland_NeighborMessage_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_outland_NeighborMessage_descriptor,
        new java.lang.String[] { "Id", "Sender", "Priority", });
    internal_static_outland_NeighbourReplyMessage_descriptor =
      getDescriptor().getMessageTypes().get(9);
    internal_static_outland_NeighbourReplyMessage_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_outland_NeighbourReplyMessage_descriptor,
        new java.lang.String[] { "Id", "Sender", "CorrelationId", "Response", });
    internal_static_outland_ShuffleMessage_descriptor =
      getDescriptor().getMessageTypes().get(10);
    internal_static_outland_ShuffleMessage_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_outland_ShuffleMessage_descriptor,
        new java.lang.String[] { "Id", "Sender", "Origin", "ExchangeList", "Ttl", });
    internal_static_outland_ShuffleReplyMessage_descriptor =
      getDescriptor().getMessageTypes().get(11);
    internal_static_outland_ShuffleReplyMessage_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_outland_ShuffleReplyMessage_descriptor,
        new java.lang.String[] { "Id", "Sender", "OriginalMessageId", "ExchangeList", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
