// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: outland-cluster.proto

package outland.cluster.proto;

public interface NeighbourReplyMessageOrBuilder extends
    // @@protoc_insertion_point(interface_extends:outland.NeighbourReplyMessage)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>optional string id = 1;</code>
   */
  java.lang.String getId();
  /**
   * <code>optional string id = 1;</code>
   */
  com.google.protobuf.ByteString
      getIdBytes();

  /**
   * <code>optional .outland.Node sender = 2;</code>
   */
  boolean hasSender();
  /**
   * <code>optional .outland.Node sender = 2;</code>
   */
  outland.cluster.proto.Node getSender();
  /**
   * <code>optional .outland.Node sender = 2;</code>
   */
  outland.cluster.proto.NodeOrBuilder getSenderOrBuilder();

  /**
   * <code>optional string correlationId = 3;</code>
   */
  java.lang.String getCorrelationId();
  /**
   * <code>optional string correlationId = 3;</code>
   */
  com.google.protobuf.ByteString
      getCorrelationIdBytes();

  /**
   * <code>optional .outland.NeighbourReplyMessage.Response response = 4;</code>
   */
  int getResponseValue();
  /**
   * <code>optional .outland.NeighbourReplyMessage.Response response = 4;</code>
   */
  outland.cluster.proto.NeighbourReplyMessage.Response getResponse();
}
