// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: outland-cluster.proto

package outland.cluster.proto;

public interface NodeOrBuilder extends
    // @@protoc_insertion_point(interface_extends:outland.Node)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>optional string id = 1;</code>
   */
  java.lang.String getId();
  /**
   * <code>optional string id = 1;</code>
   */
  com.google.protobuf.ByteString
      getIdBytes();

  /**
   * <code>optional string host = 2;</code>
   */
  java.lang.String getHost();
  /**
   * <code>optional string host = 2;</code>
   */
  com.google.protobuf.ByteString
      getHostBytes();

  /**
   * <code>optional int32 port = 3;</code>
   */
  int getPort();
}
