// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: outland-cluster.proto

package outland.cluster.proto;

public interface ShuffleReplyMessageOrBuilder extends
    // @@protoc_insertion_point(interface_extends:outland.ShuffleReplyMessage)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>optional string id = 1;</code>
   */
  java.lang.String getId();
  /**
   * <code>optional string id = 1;</code>
   */
  com.google.protobuf.ByteString
      getIdBytes();

  /**
   * <code>optional .outland.Node sender = 2;</code>
   */
  boolean hasSender();
  /**
   * <code>optional .outland.Node sender = 2;</code>
   */
  outland.cluster.proto.Node getSender();
  /**
   * <code>optional .outland.Node sender = 2;</code>
   */
  outland.cluster.proto.NodeOrBuilder getSenderOrBuilder();

  /**
   * <code>optional string originalMessageId = 3;</code>
   */
  java.lang.String getOriginalMessageId();
  /**
   * <code>optional string originalMessageId = 3;</code>
   */
  com.google.protobuf.ByteString
      getOriginalMessageIdBytes();

  /**
   * <code>repeated .outland.Node exchangeList = 4;</code>
   */
  java.util.List<outland.cluster.proto.Node> 
      getExchangeListList();
  /**
   * <code>repeated .outland.Node exchangeList = 4;</code>
   */
  outland.cluster.proto.Node getExchangeList(int index);
  /**
   * <code>repeated .outland.Node exchangeList = 4;</code>
   */
  int getExchangeListCount();
  /**
   * <code>repeated .outland.Node exchangeList = 4;</code>
   */
  java.util.List<? extends outland.cluster.proto.NodeOrBuilder> 
      getExchangeListOrBuilderList();
  /**
   * <code>repeated .outland.Node exchangeList = 4;</code>
   */
  outland.cluster.proto.NodeOrBuilder getExchangeListOrBuilder(
      int index);
}
