// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: outland.proto

package outland.feature.proto;

/**
 * Protobuf type {@code outland.App}
 */
public  final class App extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:outland.App)
    AppOrBuilder {
  // Use App.newBuilder() to construct.
  private App(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private App() {
    type_ = "";
    id_ = "";
    key_ = "";
    name_ = "";
    created_ = "";
    updated_ = "";
    owners_ = java.util.Collections.emptyList();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
  }
  private App(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    int mutable_bitField0_ = 0;
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          default: {
            if (!input.skipField(tag)) {
              done = true;
            }
            break;
          }
          case 10: {
            java.lang.String s = input.readStringRequireUtf8();

            id_ = s;
            break;
          }
          case 18: {
            java.lang.String s = input.readStringRequireUtf8();

            key_ = s;
            break;
          }
          case 26: {
            java.lang.String s = input.readStringRequireUtf8();

            name_ = s;
            break;
          }
          case 42: {
            if (!((mutable_bitField0_ & 0x00000040) == 0x00000040)) {
              owners_ = new java.util.ArrayList<outland.feature.proto.Owner>();
              mutable_bitField0_ |= 0x00000040;
            }
            owners_.add(
                input.readMessage(outland.feature.proto.Owner.parser(), extensionRegistry));
            break;
          }
          case 50: {
            java.lang.String s = input.readStringRequireUtf8();

            created_ = s;
            break;
          }
          case 58: {
            java.lang.String s = input.readStringRequireUtf8();

            updated_ = s;
            break;
          }
          case 66: {
            java.lang.String s = input.readStringRequireUtf8();

            type_ = s;
            break;
          }
          case 74: {
            outland.feature.proto.GrantCollection.Builder subBuilder = null;
            if (granted_ != null) {
              subBuilder = granted_.toBuilder();
            }
            granted_ = input.readMessage(outland.feature.proto.GrantCollection.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom(granted_);
              granted_ = subBuilder.buildPartial();
            }

            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      if (((mutable_bitField0_ & 0x00000040) == 0x00000040)) {
        owners_ = java.util.Collections.unmodifiableList(owners_);
      }
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return outland.feature.proto.FeatureMessage.internal_static_outland_App_descriptor;
  }

  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return outland.feature.proto.FeatureMessage.internal_static_outland_App_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            outland.feature.proto.App.class, outland.feature.proto.App.Builder.class);
  }

  private int bitField0_;
  public static final int TYPE_FIELD_NUMBER = 8;
  private volatile java.lang.Object type_;
  /**
   * <code>optional string type = 8;</code>
   */
  public java.lang.String getType() {
    java.lang.Object ref = type_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      type_ = s;
      return s;
    }
  }
  /**
   * <code>optional string type = 8;</code>
   */
  public com.google.protobuf.ByteString
      getTypeBytes() {
    java.lang.Object ref = type_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      type_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int ID_FIELD_NUMBER = 1;
  private volatile java.lang.Object id_;
  /**
   * <code>optional string id = 1;</code>
   */
  public java.lang.String getId() {
    java.lang.Object ref = id_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      id_ = s;
      return s;
    }
  }
  /**
   * <code>optional string id = 1;</code>
   */
  public com.google.protobuf.ByteString
      getIdBytes() {
    java.lang.Object ref = id_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      id_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int KEY_FIELD_NUMBER = 2;
  private volatile java.lang.Object key_;
  /**
   * <code>optional string key = 2;</code>
   */
  public java.lang.String getKey() {
    java.lang.Object ref = key_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      key_ = s;
      return s;
    }
  }
  /**
   * <code>optional string key = 2;</code>
   */
  public com.google.protobuf.ByteString
      getKeyBytes() {
    java.lang.Object ref = key_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      key_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int NAME_FIELD_NUMBER = 3;
  private volatile java.lang.Object name_;
  /**
   * <code>optional string name = 3;</code>
   */
  public java.lang.String getName() {
    java.lang.Object ref = name_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      name_ = s;
      return s;
    }
  }
  /**
   * <code>optional string name = 3;</code>
   */
  public com.google.protobuf.ByteString
      getNameBytes() {
    java.lang.Object ref = name_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      name_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int CREATED_FIELD_NUMBER = 6;
  private volatile java.lang.Object created_;
  /**
   * <code>optional string created = 6;</code>
   */
  public java.lang.String getCreated() {
    java.lang.Object ref = created_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      created_ = s;
      return s;
    }
  }
  /**
   * <code>optional string created = 6;</code>
   */
  public com.google.protobuf.ByteString
      getCreatedBytes() {
    java.lang.Object ref = created_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      created_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int UPDATED_FIELD_NUMBER = 7;
  private volatile java.lang.Object updated_;
  /**
   * <code>optional string updated = 7;</code>
   */
  public java.lang.String getUpdated() {
    java.lang.Object ref = updated_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      updated_ = s;
      return s;
    }
  }
  /**
   * <code>optional string updated = 7;</code>
   */
  public com.google.protobuf.ByteString
      getUpdatedBytes() {
    java.lang.Object ref = updated_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      updated_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int OWNERS_FIELD_NUMBER = 5;
  private java.util.List<outland.feature.proto.Owner> owners_;
  /**
   * <code>repeated .outland.Owner owners = 5;</code>
   */
  public java.util.List<outland.feature.proto.Owner> getOwnersList() {
    return owners_;
  }
  /**
   * <code>repeated .outland.Owner owners = 5;</code>
   */
  public java.util.List<? extends outland.feature.proto.OwnerOrBuilder> 
      getOwnersOrBuilderList() {
    return owners_;
  }
  /**
   * <code>repeated .outland.Owner owners = 5;</code>
   */
  public int getOwnersCount() {
    return owners_.size();
  }
  /**
   * <code>repeated .outland.Owner owners = 5;</code>
   */
  public outland.feature.proto.Owner getOwners(int index) {
    return owners_.get(index);
  }
  /**
   * <code>repeated .outland.Owner owners = 5;</code>
   */
  public outland.feature.proto.OwnerOrBuilder getOwnersOrBuilder(
      int index) {
    return owners_.get(index);
  }

  public static final int GRANTED_FIELD_NUMBER = 9;
  private outland.feature.proto.GrantCollection granted_;
  /**
   * <code>optional .outland.GrantCollection granted = 9;</code>
   */
  public boolean hasGranted() {
    return granted_ != null;
  }
  /**
   * <code>optional .outland.GrantCollection granted = 9;</code>
   */
  public outland.feature.proto.GrantCollection getGranted() {
    return granted_ == null ? outland.feature.proto.GrantCollection.getDefaultInstance() : granted_;
  }
  /**
   * <code>optional .outland.GrantCollection granted = 9;</code>
   */
  public outland.feature.proto.GrantCollectionOrBuilder getGrantedOrBuilder() {
    return getGranted();
  }

  private byte memoizedIsInitialized = -1;
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (!getIdBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 1, id_);
    }
    if (!getKeyBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 2, key_);
    }
    if (!getNameBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 3, name_);
    }
    for (int i = 0; i < owners_.size(); i++) {
      output.writeMessage(5, owners_.get(i));
    }
    if (!getCreatedBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 6, created_);
    }
    if (!getUpdatedBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 7, updated_);
    }
    if (!getTypeBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 8, type_);
    }
    if (granted_ != null) {
      output.writeMessage(9, getGranted());
    }
  }

  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (!getIdBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, id_);
    }
    if (!getKeyBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, key_);
    }
    if (!getNameBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, name_);
    }
    for (int i = 0; i < owners_.size(); i++) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(5, owners_.get(i));
    }
    if (!getCreatedBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(6, created_);
    }
    if (!getUpdatedBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(7, updated_);
    }
    if (!getTypeBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(8, type_);
    }
    if (granted_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(9, getGranted());
    }
    memoizedSize = size;
    return size;
  }

  private static final long serialVersionUID = 0L;
  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof outland.feature.proto.App)) {
      return super.equals(obj);
    }
    outland.feature.proto.App other = (outland.feature.proto.App) obj;

    boolean result = true;
    result = result && getType()
        .equals(other.getType());
    result = result && getId()
        .equals(other.getId());
    result = result && getKey()
        .equals(other.getKey());
    result = result && getName()
        .equals(other.getName());
    result = result && getCreated()
        .equals(other.getCreated());
    result = result && getUpdated()
        .equals(other.getUpdated());
    result = result && getOwnersList()
        .equals(other.getOwnersList());
    result = result && (hasGranted() == other.hasGranted());
    if (hasGranted()) {
      result = result && getGranted()
          .equals(other.getGranted());
    }
    return result;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptorForType().hashCode();
    hash = (37 * hash) + TYPE_FIELD_NUMBER;
    hash = (53 * hash) + getType().hashCode();
    hash = (37 * hash) + ID_FIELD_NUMBER;
    hash = (53 * hash) + getId().hashCode();
    hash = (37 * hash) + KEY_FIELD_NUMBER;
    hash = (53 * hash) + getKey().hashCode();
    hash = (37 * hash) + NAME_FIELD_NUMBER;
    hash = (53 * hash) + getName().hashCode();
    hash = (37 * hash) + CREATED_FIELD_NUMBER;
    hash = (53 * hash) + getCreated().hashCode();
    hash = (37 * hash) + UPDATED_FIELD_NUMBER;
    hash = (53 * hash) + getUpdated().hashCode();
    if (getOwnersCount() > 0) {
      hash = (37 * hash) + OWNERS_FIELD_NUMBER;
      hash = (53 * hash) + getOwnersList().hashCode();
    }
    if (hasGranted()) {
      hash = (37 * hash) + GRANTED_FIELD_NUMBER;
      hash = (53 * hash) + getGranted().hashCode();
    }
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static outland.feature.proto.App parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static outland.feature.proto.App parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static outland.feature.proto.App parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static outland.feature.proto.App parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static outland.feature.proto.App parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static outland.feature.proto.App parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static outland.feature.proto.App parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static outland.feature.proto.App parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static outland.feature.proto.App parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static outland.feature.proto.App parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(outland.feature.proto.App prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code outland.App}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:outland.App)
      outland.feature.proto.AppOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return outland.feature.proto.FeatureMessage.internal_static_outland_App_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return outland.feature.proto.FeatureMessage.internal_static_outland_App_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              outland.feature.proto.App.class, outland.feature.proto.App.Builder.class);
    }

    // Construct using outland.feature.proto.App.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
        getOwnersFieldBuilder();
      }
    }
    public Builder clear() {
      super.clear();
      type_ = "";

      id_ = "";

      key_ = "";

      name_ = "";

      created_ = "";

      updated_ = "";

      if (ownersBuilder_ == null) {
        owners_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000040);
      } else {
        ownersBuilder_.clear();
      }
      if (grantedBuilder_ == null) {
        granted_ = null;
      } else {
        granted_ = null;
        grantedBuilder_ = null;
      }
      return this;
    }

    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return outland.feature.proto.FeatureMessage.internal_static_outland_App_descriptor;
    }

    public outland.feature.proto.App getDefaultInstanceForType() {
      return outland.feature.proto.App.getDefaultInstance();
    }

    public outland.feature.proto.App build() {
      outland.feature.proto.App result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    public outland.feature.proto.App buildPartial() {
      outland.feature.proto.App result = new outland.feature.proto.App(this);
      int from_bitField0_ = bitField0_;
      int to_bitField0_ = 0;
      result.type_ = type_;
      result.id_ = id_;
      result.key_ = key_;
      result.name_ = name_;
      result.created_ = created_;
      result.updated_ = updated_;
      if (ownersBuilder_ == null) {
        if (((bitField0_ & 0x00000040) == 0x00000040)) {
          owners_ = java.util.Collections.unmodifiableList(owners_);
          bitField0_ = (bitField0_ & ~0x00000040);
        }
        result.owners_ = owners_;
      } else {
        result.owners_ = ownersBuilder_.build();
      }
      if (grantedBuilder_ == null) {
        result.granted_ = granted_;
      } else {
        result.granted_ = grantedBuilder_.build();
      }
      result.bitField0_ = to_bitField0_;
      onBuilt();
      return result;
    }

    public Builder clone() {
      return (Builder) super.clone();
    }
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        Object value) {
      return (Builder) super.setField(field, value);
    }
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return (Builder) super.clearField(field);
    }
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return (Builder) super.clearOneof(oneof);
    }
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, Object value) {
      return (Builder) super.setRepeatedField(field, index, value);
    }
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        Object value) {
      return (Builder) super.addRepeatedField(field, value);
    }
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof outland.feature.proto.App) {
        return mergeFrom((outland.feature.proto.App)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(outland.feature.proto.App other) {
      if (other == outland.feature.proto.App.getDefaultInstance()) return this;
      if (!other.getType().isEmpty()) {
        type_ = other.type_;
        onChanged();
      }
      if (!other.getId().isEmpty()) {
        id_ = other.id_;
        onChanged();
      }
      if (!other.getKey().isEmpty()) {
        key_ = other.key_;
        onChanged();
      }
      if (!other.getName().isEmpty()) {
        name_ = other.name_;
        onChanged();
      }
      if (!other.getCreated().isEmpty()) {
        created_ = other.created_;
        onChanged();
      }
      if (!other.getUpdated().isEmpty()) {
        updated_ = other.updated_;
        onChanged();
      }
      if (ownersBuilder_ == null) {
        if (!other.owners_.isEmpty()) {
          if (owners_.isEmpty()) {
            owners_ = other.owners_;
            bitField0_ = (bitField0_ & ~0x00000040);
          } else {
            ensureOwnersIsMutable();
            owners_.addAll(other.owners_);
          }
          onChanged();
        }
      } else {
        if (!other.owners_.isEmpty()) {
          if (ownersBuilder_.isEmpty()) {
            ownersBuilder_.dispose();
            ownersBuilder_ = null;
            owners_ = other.owners_;
            bitField0_ = (bitField0_ & ~0x00000040);
            ownersBuilder_ = 
              com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                 getOwnersFieldBuilder() : null;
          } else {
            ownersBuilder_.addAllMessages(other.owners_);
          }
        }
      }
      if (other.hasGranted()) {
        mergeGranted(other.getGranted());
      }
      onChanged();
      return this;
    }

    public final boolean isInitialized() {
      return true;
    }

    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      outland.feature.proto.App parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (outland.feature.proto.App) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }
    private int bitField0_;

    private java.lang.Object type_ = "";
    /**
     * <code>optional string type = 8;</code>
     */
    public java.lang.String getType() {
      java.lang.Object ref = type_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        type_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>optional string type = 8;</code>
     */
    public com.google.protobuf.ByteString
        getTypeBytes() {
      java.lang.Object ref = type_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        type_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>optional string type = 8;</code>
     */
    public Builder setType(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      type_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>optional string type = 8;</code>
     */
    public Builder clearType() {
      
      type_ = getDefaultInstance().getType();
      onChanged();
      return this;
    }
    /**
     * <code>optional string type = 8;</code>
     */
    public Builder setTypeBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      type_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object id_ = "";
    /**
     * <code>optional string id = 1;</code>
     */
    public java.lang.String getId() {
      java.lang.Object ref = id_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        id_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>optional string id = 1;</code>
     */
    public com.google.protobuf.ByteString
        getIdBytes() {
      java.lang.Object ref = id_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        id_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>optional string id = 1;</code>
     */
    public Builder setId(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      id_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>optional string id = 1;</code>
     */
    public Builder clearId() {
      
      id_ = getDefaultInstance().getId();
      onChanged();
      return this;
    }
    /**
     * <code>optional string id = 1;</code>
     */
    public Builder setIdBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      id_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object key_ = "";
    /**
     * <code>optional string key = 2;</code>
     */
    public java.lang.String getKey() {
      java.lang.Object ref = key_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        key_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>optional string key = 2;</code>
     */
    public com.google.protobuf.ByteString
        getKeyBytes() {
      java.lang.Object ref = key_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        key_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>optional string key = 2;</code>
     */
    public Builder setKey(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      key_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>optional string key = 2;</code>
     */
    public Builder clearKey() {
      
      key_ = getDefaultInstance().getKey();
      onChanged();
      return this;
    }
    /**
     * <code>optional string key = 2;</code>
     */
    public Builder setKeyBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      key_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object name_ = "";
    /**
     * <code>optional string name = 3;</code>
     */
    public java.lang.String getName() {
      java.lang.Object ref = name_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        name_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>optional string name = 3;</code>
     */
    public com.google.protobuf.ByteString
        getNameBytes() {
      java.lang.Object ref = name_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        name_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>optional string name = 3;</code>
     */
    public Builder setName(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      name_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>optional string name = 3;</code>
     */
    public Builder clearName() {
      
      name_ = getDefaultInstance().getName();
      onChanged();
      return this;
    }
    /**
     * <code>optional string name = 3;</code>
     */
    public Builder setNameBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      name_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object created_ = "";
    /**
     * <code>optional string created = 6;</code>
     */
    public java.lang.String getCreated() {
      java.lang.Object ref = created_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        created_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>optional string created = 6;</code>
     */
    public com.google.protobuf.ByteString
        getCreatedBytes() {
      java.lang.Object ref = created_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        created_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>optional string created = 6;</code>
     */
    public Builder setCreated(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      created_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>optional string created = 6;</code>
     */
    public Builder clearCreated() {
      
      created_ = getDefaultInstance().getCreated();
      onChanged();
      return this;
    }
    /**
     * <code>optional string created = 6;</code>
     */
    public Builder setCreatedBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      created_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object updated_ = "";
    /**
     * <code>optional string updated = 7;</code>
     */
    public java.lang.String getUpdated() {
      java.lang.Object ref = updated_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        updated_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>optional string updated = 7;</code>
     */
    public com.google.protobuf.ByteString
        getUpdatedBytes() {
      java.lang.Object ref = updated_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        updated_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>optional string updated = 7;</code>
     */
    public Builder setUpdated(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      updated_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>optional string updated = 7;</code>
     */
    public Builder clearUpdated() {
      
      updated_ = getDefaultInstance().getUpdated();
      onChanged();
      return this;
    }
    /**
     * <code>optional string updated = 7;</code>
     */
    public Builder setUpdatedBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      updated_ = value;
      onChanged();
      return this;
    }

    private java.util.List<outland.feature.proto.Owner> owners_ =
      java.util.Collections.emptyList();
    private void ensureOwnersIsMutable() {
      if (!((bitField0_ & 0x00000040) == 0x00000040)) {
        owners_ = new java.util.ArrayList<outland.feature.proto.Owner>(owners_);
        bitField0_ |= 0x00000040;
       }
    }

    private com.google.protobuf.RepeatedFieldBuilderV3<
        outland.feature.proto.Owner, outland.feature.proto.Owner.Builder, outland.feature.proto.OwnerOrBuilder> ownersBuilder_;

    /**
     * <code>repeated .outland.Owner owners = 5;</code>
     */
    public java.util.List<outland.feature.proto.Owner> getOwnersList() {
      if (ownersBuilder_ == null) {
        return java.util.Collections.unmodifiableList(owners_);
      } else {
        return ownersBuilder_.getMessageList();
      }
    }
    /**
     * <code>repeated .outland.Owner owners = 5;</code>
     */
    public int getOwnersCount() {
      if (ownersBuilder_ == null) {
        return owners_.size();
      } else {
        return ownersBuilder_.getCount();
      }
    }
    /**
     * <code>repeated .outland.Owner owners = 5;</code>
     */
    public outland.feature.proto.Owner getOwners(int index) {
      if (ownersBuilder_ == null) {
        return owners_.get(index);
      } else {
        return ownersBuilder_.getMessage(index);
      }
    }
    /**
     * <code>repeated .outland.Owner owners = 5;</code>
     */
    public Builder setOwners(
        int index, outland.feature.proto.Owner value) {
      if (ownersBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureOwnersIsMutable();
        owners_.set(index, value);
        onChanged();
      } else {
        ownersBuilder_.setMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .outland.Owner owners = 5;</code>
     */
    public Builder setOwners(
        int index, outland.feature.proto.Owner.Builder builderForValue) {
      if (ownersBuilder_ == null) {
        ensureOwnersIsMutable();
        owners_.set(index, builderForValue.build());
        onChanged();
      } else {
        ownersBuilder_.setMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .outland.Owner owners = 5;</code>
     */
    public Builder addOwners(outland.feature.proto.Owner value) {
      if (ownersBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureOwnersIsMutable();
        owners_.add(value);
        onChanged();
      } else {
        ownersBuilder_.addMessage(value);
      }
      return this;
    }
    /**
     * <code>repeated .outland.Owner owners = 5;</code>
     */
    public Builder addOwners(
        int index, outland.feature.proto.Owner value) {
      if (ownersBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureOwnersIsMutable();
        owners_.add(index, value);
        onChanged();
      } else {
        ownersBuilder_.addMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .outland.Owner owners = 5;</code>
     */
    public Builder addOwners(
        outland.feature.proto.Owner.Builder builderForValue) {
      if (ownersBuilder_ == null) {
        ensureOwnersIsMutable();
        owners_.add(builderForValue.build());
        onChanged();
      } else {
        ownersBuilder_.addMessage(builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .outland.Owner owners = 5;</code>
     */
    public Builder addOwners(
        int index, outland.feature.proto.Owner.Builder builderForValue) {
      if (ownersBuilder_ == null) {
        ensureOwnersIsMutable();
        owners_.add(index, builderForValue.build());
        onChanged();
      } else {
        ownersBuilder_.addMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .outland.Owner owners = 5;</code>
     */
    public Builder addAllOwners(
        java.lang.Iterable<? extends outland.feature.proto.Owner> values) {
      if (ownersBuilder_ == null) {
        ensureOwnersIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, owners_);
        onChanged();
      } else {
        ownersBuilder_.addAllMessages(values);
      }
      return this;
    }
    /**
     * <code>repeated .outland.Owner owners = 5;</code>
     */
    public Builder clearOwners() {
      if (ownersBuilder_ == null) {
        owners_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000040);
        onChanged();
      } else {
        ownersBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>repeated .outland.Owner owners = 5;</code>
     */
    public Builder removeOwners(int index) {
      if (ownersBuilder_ == null) {
        ensureOwnersIsMutable();
        owners_.remove(index);
        onChanged();
      } else {
        ownersBuilder_.remove(index);
      }
      return this;
    }
    /**
     * <code>repeated .outland.Owner owners = 5;</code>
     */
    public outland.feature.proto.Owner.Builder getOwnersBuilder(
        int index) {
      return getOwnersFieldBuilder().getBuilder(index);
    }
    /**
     * <code>repeated .outland.Owner owners = 5;</code>
     */
    public outland.feature.proto.OwnerOrBuilder getOwnersOrBuilder(
        int index) {
      if (ownersBuilder_ == null) {
        return owners_.get(index);  } else {
        return ownersBuilder_.getMessageOrBuilder(index);
      }
    }
    /**
     * <code>repeated .outland.Owner owners = 5;</code>
     */
    public java.util.List<? extends outland.feature.proto.OwnerOrBuilder> 
         getOwnersOrBuilderList() {
      if (ownersBuilder_ != null) {
        return ownersBuilder_.getMessageOrBuilderList();
      } else {
        return java.util.Collections.unmodifiableList(owners_);
      }
    }
    /**
     * <code>repeated .outland.Owner owners = 5;</code>
     */
    public outland.feature.proto.Owner.Builder addOwnersBuilder() {
      return getOwnersFieldBuilder().addBuilder(
          outland.feature.proto.Owner.getDefaultInstance());
    }
    /**
     * <code>repeated .outland.Owner owners = 5;</code>
     */
    public outland.feature.proto.Owner.Builder addOwnersBuilder(
        int index) {
      return getOwnersFieldBuilder().addBuilder(
          index, outland.feature.proto.Owner.getDefaultInstance());
    }
    /**
     * <code>repeated .outland.Owner owners = 5;</code>
     */
    public java.util.List<outland.feature.proto.Owner.Builder> 
         getOwnersBuilderList() {
      return getOwnersFieldBuilder().getBuilderList();
    }
    private com.google.protobuf.RepeatedFieldBuilderV3<
        outland.feature.proto.Owner, outland.feature.proto.Owner.Builder, outland.feature.proto.OwnerOrBuilder> 
        getOwnersFieldBuilder() {
      if (ownersBuilder_ == null) {
        ownersBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
            outland.feature.proto.Owner, outland.feature.proto.Owner.Builder, outland.feature.proto.OwnerOrBuilder>(
                owners_,
                ((bitField0_ & 0x00000040) == 0x00000040),
                getParentForChildren(),
                isClean());
        owners_ = null;
      }
      return ownersBuilder_;
    }

    private outland.feature.proto.GrantCollection granted_ = null;
    private com.google.protobuf.SingleFieldBuilderV3<
        outland.feature.proto.GrantCollection, outland.feature.proto.GrantCollection.Builder, outland.feature.proto.GrantCollectionOrBuilder> grantedBuilder_;
    /**
     * <code>optional .outland.GrantCollection granted = 9;</code>
     */
    public boolean hasGranted() {
      return grantedBuilder_ != null || granted_ != null;
    }
    /**
     * <code>optional .outland.GrantCollection granted = 9;</code>
     */
    public outland.feature.proto.GrantCollection getGranted() {
      if (grantedBuilder_ == null) {
        return granted_ == null ? outland.feature.proto.GrantCollection.getDefaultInstance() : granted_;
      } else {
        return grantedBuilder_.getMessage();
      }
    }
    /**
     * <code>optional .outland.GrantCollection granted = 9;</code>
     */
    public Builder setGranted(outland.feature.proto.GrantCollection value) {
      if (grantedBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        granted_ = value;
        onChanged();
      } else {
        grantedBuilder_.setMessage(value);
      }

      return this;
    }
    /**
     * <code>optional .outland.GrantCollection granted = 9;</code>
     */
    public Builder setGranted(
        outland.feature.proto.GrantCollection.Builder builderForValue) {
      if (grantedBuilder_ == null) {
        granted_ = builderForValue.build();
        onChanged();
      } else {
        grantedBuilder_.setMessage(builderForValue.build());
      }

      return this;
    }
    /**
     * <code>optional .outland.GrantCollection granted = 9;</code>
     */
    public Builder mergeGranted(outland.feature.proto.GrantCollection value) {
      if (grantedBuilder_ == null) {
        if (granted_ != null) {
          granted_ =
            outland.feature.proto.GrantCollection.newBuilder(granted_).mergeFrom(value).buildPartial();
        } else {
          granted_ = value;
        }
        onChanged();
      } else {
        grantedBuilder_.mergeFrom(value);
      }

      return this;
    }
    /**
     * <code>optional .outland.GrantCollection granted = 9;</code>
     */
    public Builder clearGranted() {
      if (grantedBuilder_ == null) {
        granted_ = null;
        onChanged();
      } else {
        granted_ = null;
        grantedBuilder_ = null;
      }

      return this;
    }
    /**
     * <code>optional .outland.GrantCollection granted = 9;</code>
     */
    public outland.feature.proto.GrantCollection.Builder getGrantedBuilder() {
      
      onChanged();
      return getGrantedFieldBuilder().getBuilder();
    }
    /**
     * <code>optional .outland.GrantCollection granted = 9;</code>
     */
    public outland.feature.proto.GrantCollectionOrBuilder getGrantedOrBuilder() {
      if (grantedBuilder_ != null) {
        return grantedBuilder_.getMessageOrBuilder();
      } else {
        return granted_ == null ?
            outland.feature.proto.GrantCollection.getDefaultInstance() : granted_;
      }
    }
    /**
     * <code>optional .outland.GrantCollection granted = 9;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        outland.feature.proto.GrantCollection, outland.feature.proto.GrantCollection.Builder, outland.feature.proto.GrantCollectionOrBuilder> 
        getGrantedFieldBuilder() {
      if (grantedBuilder_ == null) {
        grantedBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            outland.feature.proto.GrantCollection, outland.feature.proto.GrantCollection.Builder, outland.feature.proto.GrantCollectionOrBuilder>(
                getGranted(),
                getParentForChildren(),
                isClean());
        granted_ = null;
      }
      return grantedBuilder_;
    }
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return this;
    }

    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return this;
    }


    // @@protoc_insertion_point(builder_scope:outland.App)
  }

  // @@protoc_insertion_point(class_scope:outland.App)
  private static final outland.feature.proto.App DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new outland.feature.proto.App();
  }

  public static outland.feature.proto.App getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<App>
      PARSER = new com.google.protobuf.AbstractParser<App>() {
    public App parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
        return new App(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<App> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<App> getParserForType() {
    return PARSER;
  }

  public outland.feature.proto.App getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

