// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: outland.proto

package outland.feature.proto;

public interface AppOrBuilder extends
    // @@protoc_insertion_point(interface_extends:outland.App)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>optional string id = 1;</code>
   */
  java.lang.String getId();
  /**
   * <code>optional string id = 1;</code>
   */
  com.google.protobuf.ByteString
      getIdBytes();

  /**
   * <code>optional string key = 2;</code>
   */
  java.lang.String getKey();
  /**
   * <code>optional string key = 2;</code>
   */
  com.google.protobuf.ByteString
      getKeyBytes();

  /**
   * <code>optional string name = 3;</code>
   */
  java.lang.String getName();
  /**
   * <code>optional string name = 3;</code>
   */
  com.google.protobuf.ByteString
      getNameBytes();

  /**
   * <code>optional string created = 6;</code>
   */
  java.lang.String getCreated();
  /**
   * <code>optional string created = 6;</code>
   */
  com.google.protobuf.ByteString
      getCreatedBytes();

  /**
   * <code>optional string updated = 7;</code>
   */
  java.lang.String getUpdated();
  /**
   * <code>optional string updated = 7;</code>
   */
  com.google.protobuf.ByteString
      getUpdatedBytes();

  /**
   * <code>repeated .outland.Service services = 4;</code>
   */
  java.util.List<outland.feature.proto.Service> 
      getServicesList();
  /**
   * <code>repeated .outland.Service services = 4;</code>
   */
  outland.feature.proto.Service getServices(int index);
  /**
   * <code>repeated .outland.Service services = 4;</code>
   */
  int getServicesCount();
  /**
   * <code>repeated .outland.Service services = 4;</code>
   */
  java.util.List<? extends outland.feature.proto.ServiceOrBuilder> 
      getServicesOrBuilderList();
  /**
   * <code>repeated .outland.Service services = 4;</code>
   */
  outland.feature.proto.ServiceOrBuilder getServicesOrBuilder(
      int index);

  /**
   * <code>repeated .outland.Owner owners = 5;</code>
   */
  java.util.List<outland.feature.proto.Owner> 
      getOwnersList();
  /**
   * <code>repeated .outland.Owner owners = 5;</code>
   */
  outland.feature.proto.Owner getOwners(int index);
  /**
   * <code>repeated .outland.Owner owners = 5;</code>
   */
  int getOwnersCount();
  /**
   * <code>repeated .outland.Owner owners = 5;</code>
   */
  java.util.List<? extends outland.feature.proto.OwnerOrBuilder> 
      getOwnersOrBuilderList();
  /**
   * <code>repeated .outland.Owner owners = 5;</code>
   */
  outland.feature.proto.OwnerOrBuilder getOwnersOrBuilder(
      int index);

  /**
   * <code>optional string type = 8;</code>
   */
  java.lang.String getType();
  /**
   * <code>optional string type = 8;</code>
   */
  com.google.protobuf.ByteString
      getTypeBytes();
}
