// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: outland.proto

package outland.feature.proto;

public interface FeatureOwnerOrBuilder extends
    // @@protoc_insertion_point(interface_extends:outland.FeatureOwner)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>optional string name = 2;</code>
   */
  java.lang.String getName();
  /**
   * <code>optional string name = 2;</code>
   */
  com.google.protobuf.ByteString
      getNameBytes();

  /**
   * <pre>
   * mappable to Owner.email
   * </pre>
   *
   * <code>optional string email = 3;</code>
   */
  java.lang.String getEmail();
  /**
   * <pre>
   * mappable to Owner.email
   * </pre>
   *
   * <code>optional string email = 3;</code>
   */
  com.google.protobuf.ByteString
      getEmailBytes();

  /**
   * <code>optional string username = 4;</code>
   */
  java.lang.String getUsername();
  /**
   * <code>optional string username = 4;</code>
   */
  com.google.protobuf.ByteString
      getUsernameBytes();
}
