// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: outland.proto

package outland.feature.proto;

public interface FeatureOptionOrBuilder extends
    // @@protoc_insertion_point(interface_extends:outland.FeatureOption)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>optional string id = 1;</code>
   */
  java.lang.String getId();
  /**
   * <code>optional string id = 1;</code>
   */
  com.google.protobuf.ByteString
      getIdBytes();

  /**
   * <code>optional .outland.OptionType optionType = 2;</code>
   */
  int getOptionTypeValue();
  /**
   * <code>optional .outland.OptionType optionType = 2;</code>
   */
  outland.feature.proto.OptionType getOptionType();

  /**
   * <code>optional string name = 3;</code>
   */
  java.lang.String getName();
  /**
   * <code>optional string name = 3;</code>
   */
  com.google.protobuf.ByteString
      getNameBytes();

  /**
   * <code>optional string value = 4;</code>
   */
  java.lang.String getValue();
  /**
   * <code>optional string value = 4;</code>
   */
  com.google.protobuf.ByteString
      getValueBytes();

  /**
   * <code>optional int32 weight = 5;</code>
   */
  int getWeight();

  /**
   * <code>optional string type = 6;</code>
   */
  java.lang.String getType();
  /**
   * <code>optional string type = 6;</code>
   */
  com.google.protobuf.ByteString
      getTypeBytes();
}
