// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: outland.proto

package outland.feature.proto;

public interface GrantCollectionOrBuilder extends
    // @@protoc_insertion_point(interface_extends:outland.GrantCollection)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>optional string type = 1;</code>
   */
  java.lang.String getType();
  /**
   * <code>optional string type = 1;</code>
   */
  com.google.protobuf.ByteString
      getTypeBytes();

  /**
   * <code>repeated .outland.ServiceGrant services = 10;</code>
   */
  java.util.List<outland.feature.proto.ServiceGrant> 
      getServicesList();
  /**
   * <code>repeated .outland.ServiceGrant services = 10;</code>
   */
  outland.feature.proto.ServiceGrant getServices(int index);
  /**
   * <code>repeated .outland.ServiceGrant services = 10;</code>
   */
  int getServicesCount();
  /**
   * <code>repeated .outland.ServiceGrant services = 10;</code>
   */
  java.util.List<? extends outland.feature.proto.ServiceGrantOrBuilder> 
      getServicesOrBuilderList();
  /**
   * <code>repeated .outland.ServiceGrant services = 10;</code>
   */
  outland.feature.proto.ServiceGrantOrBuilder getServicesOrBuilder(
      int index);

  /**
   * <code>repeated .outland.MemberGrant members = 11;</code>
   */
  java.util.List<outland.feature.proto.MemberGrant> 
      getMembersList();
  /**
   * <code>repeated .outland.MemberGrant members = 11;</code>
   */
  outland.feature.proto.MemberGrant getMembers(int index);
  /**
   * <code>repeated .outland.MemberGrant members = 11;</code>
   */
  int getMembersCount();
  /**
   * <code>repeated .outland.MemberGrant members = 11;</code>
   */
  java.util.List<? extends outland.feature.proto.MemberGrantOrBuilder> 
      getMembersOrBuilderList();
  /**
   * <code>repeated .outland.MemberGrant members = 11;</code>
   */
  outland.feature.proto.MemberGrantOrBuilder getMembersOrBuilder(
      int index);
}
