// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: outland.proto

package outland.feature.proto;

public interface OptionCollectionOrBuilder extends
    // @@protoc_insertion_point(interface_extends:outland.OptionCollection)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>optional string type = 1;</code>
   */
  java.lang.String getType();
  /**
   * <code>optional string type = 1;</code>
   */
  com.google.protobuf.ByteString
      getTypeBytes();

  /**
   * <code>optional .outland.OptionType option = 2;</code>
   */
  int getOptionValue();
  /**
   * <code>optional .outland.OptionType option = 2;</code>
   */
  outland.feature.proto.OptionType getOption();

  /**
   * <code>optional int32 maxweight = 3;</code>
   */
  int getMaxweight();

  /**
   * <code>repeated .outland.FeatureOption items = 4;</code>
   */
  java.util.List<outland.feature.proto.FeatureOption> 
      getItemsList();
  /**
   * <code>repeated .outland.FeatureOption items = 4;</code>
   */
  outland.feature.proto.FeatureOption getItems(int index);
  /**
   * <code>repeated .outland.FeatureOption items = 4;</code>
   */
  int getItemsCount();
  /**
   * <code>repeated .outland.FeatureOption items = 4;</code>
   */
  java.util.List<? extends outland.feature.proto.FeatureOptionOrBuilder> 
      getItemsOrBuilderList();
  /**
   * <code>repeated .outland.FeatureOption items = 4;</code>
   */
  outland.feature.proto.FeatureOptionOrBuilder getItemsOrBuilder(
      int index);
}
