serviceName: Outland Feature Service
environment: development

baseURI: http://localhost:8180

server:
  registerDefaultExceptionMappers: false
  applicationConnectors:
    - type: http
      port: 8280
      idleTimeout: 8 seconds
  adminConnectors:
    - type: http
      port: 8281

redis:
  servers:
    - name: outland_feature_cache_redis
      host: localhost
      port: 6379
      maxConnections: 8
    - name: outland_feature_idempotency_check_redis
      host: localhost
      port: 6379
      maxConnections: 8

logging:
  level: INFO
  appenders:
    - type: console
      timeZone: UTC
      threshold: INFO
      target: stderr
    - type: file
      currentLogFilename: /tmp/application.log
      archive: false
      timeZone: UTC

aws:
  environment: test
  accessKey: AWS_KEY
  secretKey: AWS_SECRET
  dynamoDbUrl: http://localhost:8000
  signingRegion: eu-central-1

featureTable:
  outlandFeaturesTable: dev_outland_features
  outlandAppsTable: dev_outland_apps
  outlandAppGraphTable: dev_outland_app_graph

auth:
  # basic exists mostly for dev, test and local docker. Always enable oauth for production. The main
  # scenario for enabling basic in prod is to allow a management ui to make requests for all apps via
  # a shared secret.
  basicEnabled: ${OUTLAND_FEATURE_AUTH_BASIC_ENABLED:-true}
  # basic_app_username_password_keys: use the values in basicAuthenticationKeys as global api keys
  basicAuthenticationPolicy: basic_app_username_password_keys
  # set a comma separated list of keys via the DW_API_KEYS envar
  basicAuthenticationKeys: ${FEATURE_API_KEYS}
  # basic_disable_scope_check: ignore scope checks for api requests
  basicScopePolicy: basic_disable_scope_check
  basicCacheCredentialSeconds: 30

  oauthEnabled: ${OUTLAND_FEATURE_AUTH_OAUTH_ENABLED:-false}
  # oauth_bearer_reflect: return the bearer token as the app id (for local testing with token services)
#  oauthAuthenticationPolicy: oauth_bearer_reflect
  oauthAuthenticationPolicy: oauth_bearer_check
  # oauth_disable_scope_check: don't check scopes
  oauthScopePolicy: oauth_disable_scope_check
  oauthCacheTokenSeconds: 30
  remoteOAuthServer:
    tokenLookupURI: ${OUTLAND_FEATURE_REMOTE_OAUTH_SERVER:-https://localhost/oauth2/tokeninfo}
    connectTimeout: 3000
    readTimeout: 3000

redisFeatureCacheHystrix:
  hystrixCommandGroupKey: redisFeatureCacheHystrix
  executionTimeoutInMilliseconds: 150
  threadpool:
    coreSize: 8

dynamodbFeatureWriteHystrix:
  hystrixCommandGroupKey: dynamodbFeatureWriteHystrix
  executionTimeoutInMilliseconds: 3000
  threadpool:
    coreSize: 8

dynamodbFeatureReadHystrix:
   hystrixCommandGroupKey: dynamodbFeatureReadHystrix
   executionTimeoutInMilliseconds: 1000
   threadpool:
     coreSize: 16

dynamodbAppGraphWriteHystrix:
  hystrixCommandGroupKey: dynamodbAppGraphWriteHystrix
  executionTimeoutInMilliseconds: 3000
  threadpool:
    coreSize: 8

dynamodbAppWriteHystrix:
  hystrixCommandGroupKey: dynamodbAppWriteHystrix
  executionTimeoutInMilliseconds: 3000
  threadpool:
    coreSize: 8

dynamodbAppGraphQueryHystrix:
  hystrixCommandGroupKey: dynamodbAppGraphQueryHystrix
  executionTimeoutInMilliseconds: 3000
  threadpool:
    coreSize: 8