serviceName: Outland Feature Service Docker
environment: docker

baseURI: http://localhost:8180

server:
  registerDefaultExceptionMappers: false
  applicationConnectors:
    - type: http
      port: 8180
      idleTimeout: 10 seconds
  adminConnectors:
    - type: http
      port: 8181

redis:
  servers:
    - name: outland_feature_cache_redis
      host: redis
      port: 6379
      maxConnections: 8
    - name: outland_feature_idempotency_check_redis
      host: redis
      port: 6379
      maxConnections: 8

logging:
  level: INFO
  loggers:
    "outland.feature.service.DefaultFeatureStorage": DEBUG
  appenders:
    - type: console
      timeZone: UTC
      threshold: INFO
      target: stderr
    - type: file
      currentLogFilename: application.log
      archive: true
      archivedFileCount: 6
      archivedLogFilenamePattern: myapplication-%d.log.gz
      timeZone: UTC

aws:
  environment: docker
  accessKey: AWS_KEY
  secretKey: AWS_SECRET
  dynamoDbUrl: http://dynamodb:8000
  signingRegion: eu-central-1

featureTable:
  outlandFeaturesTable: dev_outland_features
  outlandAppsTable: dev_outland_apps
  outlandAppGraphTable: dev_outland_app_graph

auth:
  basicEnabled: true
  basicAuthenticationPolicy: basic_app_username_password_keys
  basicAuthenticationKeys: ${FEATURE_API_KEYS}
  basicScopePolicy: basic_disable_scope_check
  basicCacheCredentialSeconds: 30

  oauthEnabled: false
  # oauth_bearer_reflect: return the bearer token as the app id (for local testing with token services)
  oauthAuthenticationPolicy: oauth_bearer_reflect
  # oauth_disable_scope_check: don't check scopes
  oauthScopePolicy: oauth_disable_scope_check
  oauthCacheTokenSeconds: 30
  remoteOAuthServer:
    tokenLookupURI: ${OUTLAND_FEATURE_REMOTE_OAUTH_SERVER:-https://localhost/oauth2/tokeninfo}
    connectTimeout: 3000
    readTimeout: 3000

redisFeatureCacheHystrix:
  hystrixCommandGroupKey: redisFeatureCacheHystrix
  executionTimeoutInMilliseconds: 3000
  threadpool:
    coreSize: 8

dynamodbFeatureWriteHystrix:
  hystrixCommandGroupKey: dynamodbFeatureWriteHystrix
  executionTimeoutInMilliseconds: 3000
  threadpool:
    coreSize: 8

dynamodbFeatureReadHystrix:
   hystrixCommandGroupKey: dynamodbFeatureReadHystrix
   executionTimeoutInMilliseconds: 1000
   threadpool:
     coreSize: 16

dynamodbAppGraphWriteHystrix:
  hystrixCommandGroupKey: dynamodbAppGraphWriteHystrix
  executionTimeoutInMilliseconds: 3000
  threadpool:
    coreSize: 8

dynamodbAppWriteHystrix:
  hystrixCommandGroupKey: dynamodbAppWriteHystrix
  executionTimeoutInMilliseconds: 3000
  threadpool:
    coreSize: 8

dynamodbAppGraphQueryHystrix:
  hystrixCommandGroupKey: dynamodbAppGraphQueryHystrix
  executionTimeoutInMilliseconds: 3000
  threadpool:
    coreSize: 8