serviceName: Outland Feature Service

baseURI: http://localhost:8280

server:
  registerDefaultExceptionMappers: false
  applicationConnectors:
    - type: http
      port: 8280
      idleTimeout: 8 seconds
  adminConnectors:
    - type: http
      port: 8281

redis:
  servers:
    - name: outland_feature_cache_redis
      host: localhost
      port: 6379
      maxConnections: 8
    - name: outland_feature_idempotency_check_redis
      host: localhost
      port: 6379
      maxConnections: 8

logging:
  level: INFO
  appenders:
    - type: console
      timeZone: UTC
      threshold: INFO
      target: stderr
    - type: file
      currentLogFilename: /tmp/application.log
      archive: false
      timeZone: UTC

aws:
  # 'chain' uses the chained lookup option; 'iam' for just iam, or, 'local' for local dynamodb
  authMode: local
  dynamoDbUrl: http://localhost:8000
  signingRegion: eu-central-1

featureTable:
  outlandFeaturesTable: dev_outland_features
  outlandAppsTable: dev_outland_apps
  outlandAppGraphTable: dev_outland_app_graph

auth:
  # basic exists mostly for dev, test and local docker. Prefer oauth for production.
  basicEnabled: ${OUTLAND_FEATURE_AUTH_BASIC_ENABLED:-true}
  # set a comma separated map of callers and api keys
  basicAuthenticationKeys: ${OUTLAND_FEATURE_AUTH_BASIC_API_KEYS}
  basicCacheCredentialSeconds: 30

  oauthEnabled: ${OUTLAND_FEATURE_AUTH_OAUTH_ENABLED:-false}
  # oauth_disable_scope_check: don't check scopes
  oauthScopePolicy: oauth_disable_scope_check
  oauthCacheTokenSeconds: 30
  remoteOAuthServer:
    tokenLookupURI: ${OUTLAND_FEATURE_REMOTE_OAUTH_SERVER:-https://localhost/oauth2/tokeninfo}
    connectTimeout: 3000
    readTimeout: 3000

  # if these services are authenticated, allow them to access any app/feature
  multipleAppAccessList: ${OUTLAND_FEATURE_ANY_APP_GRANT:-outland.feature.ui,acme.thread.safe}


redisFeatureCacheHystrix:
  hystrixCommandGroupKey: redisFeatureCacheHystrix
  executionTimeoutInMilliseconds: 150
  threadpool:
    coreSize: 8

dynamodbFeatureWriteHystrix:
  hystrixCommandGroupKey: dynamodbFeatureWriteHystrix
  executionTimeoutInMilliseconds: 3000
  threadpool:
    coreSize: 8

dynamodbFeatureReadHystrix:
   hystrixCommandGroupKey: dynamodbFeatureReadHystrix
   executionTimeoutInMilliseconds: 1000
   threadpool:
     coreSize: 16

dynamodbAppGraphWriteHystrix:
  hystrixCommandGroupKey: dynamodbAppGraphWriteHystrix
  executionTimeoutInMilliseconds: 3000
  threadpool:
    coreSize: 8

dynamodbAppWriteHystrix:
  hystrixCommandGroupKey: dynamodbAppWriteHystrix
  executionTimeoutInMilliseconds: 3000
  threadpool:
    coreSize: 8

dynamodbAppGraphQueryHystrix:
  hystrixCommandGroupKey: dynamodbAppGraphQueryHystrix
  executionTimeoutInMilliseconds: 3000
  threadpool:
    coreSize: 8